name: Build Docker Images with NDK

on:
  push:
    branches: [ master ]

jobs:
  android-build-ndk:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        sdk: [Legacy, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
    name: SDK ${{ matrix.sdk }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image for SDK ${{ matrix.sdk }}
        env:
          SDKVER: ${{ matrix.sdk }}
        run: |
          docker build --pull -t itachi1706/docker-android-alpine-sdk:base-ndk -f ndk.Dockerfile .
          cd history
          chmod +x build.sh
          ./build.sh $SDKVER.txt Dockerfile
  android-build-no-ndk:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        sdk: [Legacy, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
    name: SDK ${{ matrix.sdk }} without NDK
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image for SDK ${{ matrix.sdk }}
        env:
          SDKVER: ${{ matrix.sdk }}
        run: |
          docker build --pull -t itachi1706/docker-android-alpine-sdk:base -f Dockerfile .
          cd history
          chmod +x build-nondk.sh
          ./build-nondk.sh $SDKVER.txt nondk.Dockerfile
